### ISSUE TITLE
device-virtual service throws below error message

### ISSUE THREAD

**Issue by Aatika-Fatima** [edgexfoundry/device-virtual#30]
2018-02-02 14:47:59.302  INFO 13272 --- [pool-9-thread-1] o.e.device.virtual.scheduling.Scheduler  : executing schedule 5a742bc65d8a0759e3a40678 'interval-for-vr-1' at 2018-02-02T14:47:59+05:30[Asia/Calcutta]
2018-02-02 14:48:02.301  INFO 13272 --- [pool-9-thread-1] o.e.device.virtual.scheduling.Scheduler  : executing schedule 5a742bc85d8a0759e3a40684 'interval-for-vr-5' at 2018-02-02T14:48:02+05:30[Asia/Calcutta]
2018-02-02 14:48:02.382 ERROR 13272 --- [askExecutor-147] o.e.d.v.s.i.CollectionTaskExecutorImpl   : update collecting scheduler failed on VirtualResource: VirtualResource [resourceId=5, deviceId=5a742bc15d8a0759e3a40673, deviceName=JC.RR5.NAE9.ConfRoom.Padre.Island01, profileId=5a742bbf5d8a0759e3a40666, profileName=JC.RR5.NAE9.ConfRoom.Padre.Island, commandId=5a742bbf5d8a0759e3a40665, commandName=SetPoint, resource=AnalogOutput_3000289, type=F, min=-99.99, max=199.99, value=-93.89, enableRandomization=true, collectionFrequency=15]
2018-02-02 14:48:02.383 ERROR 13272 --- [askExecutor-147] o.e.d.v.s.i.CollectionTaskExecutorImpl   : javax.ws.rs.ProcessingException: org.apache.http.MalformedChunkCodingException: Bad chunk header: 
2018-02-02 14:48:02.386 ERROR 13272 --- [askExecutor-147] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected error occurred invoking async method 'public void org.edgexfoundry.device.virtual.service.impl.CollectionTaskExecutorImpl.executeCollectionTask(org.edgexfoundry.device.virtual.domain.VirtualResource)'.

org.edgexfoundry.exception.controller.ServiceException: Service issue: javax.ws.rs.ProcessingException: org.apache.http.MalformedChunkCodingException: Bad chunk header: 
	at org.edgexfoundry.device.virtual.service.impl.CollectionTaskExecutorImpl.updateCollectionSchedule(CollectionTaskExecutorImpl.java:113) ~[classes/:na]
	at org.edgexfoundry.device.virtual.service.impl.CollectionTaskExecutorImpl.executeCollectionTask(CollectionTaskExecutorImpl.java:82) ~[classes/:na]
	at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_101]
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302) ~[spring-aop-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190) ~[spring-aop-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157) ~[spring-aop-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:115) ~[spring-aop-4.2.8.RELEASE.jar:4.2.8.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
	Suppressed: javax.ws.rs.client.ResponseProcessingException: javax.ws.rs.ProcessingException: org.apache.http.MalformedChunkCodingException: Bad chunk header: 
		at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:141) ~[resteasy-client-3.0.13.Final.jar:3.0.13.Final]
		at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:59) ~[resteasy-client-3.0.13.Final.jar:3.0.13.Final]
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:104) ~[resteasy-client-3.0.13.Final.jar:3.0.13.Final]
		at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:64) ~[resteasy-client-3.0.13.Final.jar:3.0.13.Final]
		at com.sun.proxy.$Proxy140.scheduleForName(Unknown Source) ~[na:na]
		at org.edgexfoundry.controller.impl.ScheduleClientImpl.scheduleForName(ScheduleClientImpl.java:53) ~[classes/:na]
		at org.edgexfoundry.device.virtual.service.impl.CollectionTaskExecutorImpl.updateCollectionSchedule(CollectionTaskExecutorImpl.java:102) ~[classes/:na]
		... 10 common frames omitted
	Caused by: javax.ws.rs.ProcessingException: org.apache.http.MalformedChunkCodingException: Bad chunk header: 
		at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:285)
		at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readEntity(ClientResponse.java:181)
		at org.jboss.resteasy.specimpl.BuiltResponse.readEntity(BuiltResponse.java:213)
		at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:105)
		... 16 common frames omitted
	Caused by: org.apache.http.MalformedChunkCodingException: Bad chunk header: 
		at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:277)
		at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
		at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
		at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
		at org.codehaus.jackson.impl.ByteSourceBootstrapper.ensureLoaded(ByteSourceBootstrapper.java:507)
		at org.codehaus.jackson.impl.ByteSourceBootstrapper.detectEncoding(ByteSourceBootstrapper.java:129)
		at org.codehaus.jackson.impl.ByteSourceBootstrapper.constructParser(ByteSourceBootstrapper.java:224)
		at org.codehaus.jackson.JsonFactory._createJsonParser(JsonFactory.java:785)
		at org.codehaus.jackson.JsonFactory.createJsonParser(JsonFactory.java:561)
		at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:414)
		at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:61)
		at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53)
		at org.jboss.resteasy.plugins.interceptors.encoding.GZIPDecodingInterceptor.aroundReadFrom(GZIPDecodingInterceptor.java:59)
		at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:55)
		at org.jboss.resteasy.client.jaxrs.internal.ClientResponse.readFrom(ClientResponse.java:251)
		... 19 common frames omitted

**Comment by tonyespy** [comment]
@Aatika-Fatima Could you please add some additional information including:

 * what release of EdgeX are you running and how (i.e. are you using the Docker containers? the snap?)

 * please include details of the hardware and OS (including version) that you're running EdgeX on

 * please include clear steps required to reproduce the problem

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
