### ISSUE TITLE
Query for a device resource with value desc specifying type=float and LSB=true fails 

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/device-virtual#33]
Platform/OS: amd64 / Ubuntu 16.04
Version: 0.5.1+cali-20180411 (snap)

A query for a device resource of **type=float** that also specifies **LSB=true**, triggers an exception in `ObjectTransform.parse()`.

Steps to reproduce, copy the [Bosch device-profile](https://github.com/edgexfoundry/device-bluetooth/blob/master/deviceprofile_samples/Bosch_XDK_profile.yaml) from device-bluetooth to one of device-virtual's sample profile directories (e.g. ./bacnet_sample_profiles), start device-virtual.

Send a query command to grab the value of a device resource (e.g. **AccelX**).  The client will hang, and after 30s, will receive a 503 (Unanticipated Error) status.  Looking at the logs shows the exception thrown when device-virtual attempted to transform the reply:

```
eObject [name=AccelX, tag=null, description=X Axis Accelerometer Reading in G-Forces, 
properties=ProfileProperty [value=PropertyValue{readWrite:R, minimum:null, maximum:null, 
defaultValue:null, size:4, precision:null, word:2, LSB:true, mask:0x00, shift:0, scale:.001, offset:0.0, 
base:0, assertion:null, signed:true}, units=org.edgexfoundry.domain.meta.Units@3403f171], 
attributes=null], attributes=org.edgexfoundry.device.virtual.domain.VirtualAttribute@3ac41981], on Device-XDK01
Exception in thread "Thread-18" org.springframework.dao.InvalidDataAccessApiUsageException: For input string: "29.02"; nested exception is java.lang.NumberFormatException: For input string: "29.02"
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:384)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:227)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:436)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:59)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:213)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:147)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at org.edgexfoundry.device.virtual.data.ObjectStore$$EnhancerBySpringCGLIB$$380dae83.put(<generated>)
	at org.edgexfoundry.device.virtual.VirtualDriver.process(VirtualDriver.java:92)
	at org.edgexfoundry.device.virtual.handler.VirtualHandler.lambda$executeOperations$0(VirtualHandler.java:191)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "29.02"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:740)
	at java.lang.Integer.decode(Integer.java:1197)
	at org.edgexfoundry.device.virtual.ObjectTransform.parse(ObjectTransform.java:101)
```

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
